name: Publish Stable

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  build:
    name: Publish Stable
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Clone GitLens
        run: git clone https://github.com/gitkraken/vscode-gitlens.git
      - name: Apply patch
        run: cd vscode-gitlens && git apply ../patches/1.patch
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10
      - name: Setup Environment
        run: cd vscode-gitlens && node -e "console.log('PACKAGE_VERSION=' + require('./package.json').version + '\nPACKAGE_NAME=' + require('./package.json').name + '-' + require('./package.json').version)" >> $GITHUB_ENV
      - name: Install
        run: cd vscode-gitlens && pnpm install
      - name: Package extension
        run: cd vscode-gitlens && pnpm run package
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}
          path: "./vscode-gitlens/*.vsix"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Release v${{ github.event.inputs.version }}
          files: ./vscode-gitlens/${{ env.PACKAGE_NAME }}-${{ env.PACKAGE_VERSION }}.vsix
          draft: false
          prerelease: false
